### ISSUE TITLE
Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.

### ISSUE THREAD

**Issue by rocketkittens** [aqwert/flutter_auth_starter#5]
I cloned the project but i can't launch the application due to this error:

`flutter_platform_widgets-0.3.1/lib/src/platform_scaffold.dart:136:26:`
`Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.`

Please advise..

**Comment by aqwert** [comment]
I am no longer supporting this project. The reason is that it uses older dependencies that were built against an older version of flutter. You will need to update the dependencies in the pubspec to try and get it to work.

However this was created in the early days of my flutter journey and probably not all that great to use

**Comment by rocketkittens** [comment]
Thank you for confirming, much appreciated!
